{
 "title": "1.Pods",
 "description": "Detailed information on Pods",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(up{service=\"k8s\"},country)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "Prod : prod, Prod-int : prod-int"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{country=\"$country\",environment=\"$env\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_deployment_created{country=\"$country\",environment=\"$env\",namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "sortby",
    "label": "Sort By",
    "query": "Pod : pod,  Container : container"
   }
  ]
 },
 "panels": [
  {
   "title": "Image Version",
   "type": "table",
   "description": "Running Image Version",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (container,image) (container_start_time_seconds{namespace=\"$namespace\", image != \"\", environment = \"$env\", country=\"$country\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Pods in  Namespace $namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{country=\"$country\", environment=\"$env\", namespace=\"$namespace\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", container!=\"\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by ($sortby) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU % Requests",
   "type": "timeseries",
   "description": "Pod CPU Request percentage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", country=\"$country\", environment= \"$env\",  platform=\"k8s\"}[1m])) by ($sortby) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod.*\", unit=\"core\", country=\"$country\", environment= \"$env\",  platform=\"k8s\"}) by ($sortby)) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU % Limits",
   "type": "timeseries",
   "description": "Pod CPU Limits percentage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", country=\"$country\", environment= \"$env\", platform=\"k8s\"}[1m])) by ($sortby) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod.*\", unit=\"core\", country=\"$country\", environment= \"$env\", platform=\"k8s\"}) by ($sortby)) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory bytes utilized by pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", container!=\"\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}) by ($sortby)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory % Limits",
   "type": "timeseries",
   "description": "Memory Percentage limits for Pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}) by ($sortby) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod.*\", unit=\"byte\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}) by ($sortby)) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory % Requests",
   "type": "timeseries",
   "description": "Memory Percentage requests for Pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod.*\", image!=\"\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod.*\", unit=\"byte\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}) by (container)) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{country=\"$country\", environment=\"$env\", namespace=\"$namespace\", pod=~\"$pod.*\", platform=\"k8s\"}) by($sortby)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Out Of Memory Kill Counter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "container_oom_events_total{namespace=\"$namespace\", country=\"$country\", environment=\"$env\", pod=~\"$pod.*\", platform=\"k8s\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Network Packets TX/RX",
   "type": "timeseries",
   "description": "Number of Packets Received and Transmitted",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "timeseries",
   "description": "Nework bytes received and Transmitted",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod.*\",country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  },
  {
   "title": "Network Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\",  platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}}Transmitted"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\",  platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}}Received"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", pod=~\"$pod.*\", country=\"$country\", environment=\"$env\", platform=\"k8s\"}[1m])) by($sortby)",
     "legendFormat": "{{pod}} Transmitted"
    }
   ]
  }
 ]
}