{
 "title": "3. Cluster Summary",
 "description": "Summary on Cluster Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(kube_node_info,country)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "Prod : prod, Prod-int : prod-int"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{country=\"$country\", environment= \"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kube_namespace_created{country=\"$country\", environment= \"$env\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "Pods that are currently running successfully",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{country=\"$country\", environment= \"$env\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "description": "Pods with Status Failed",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{country=\"$country\", environment= \"$env\", phase=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "description": "Pods with Status pending",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{country=\"$country\", environment= \"$env\", phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown Pods",
   "type": "stat",
   "description": "Pods with Status unkown",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{country=\"$country\", environment= \"$env\", phase=\"Unknown\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU % Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg(1-rate(node_cpu_seconds_total{mode=\"idle\", country=\"$country\", environment=\"$env\"}[1m]))) * 100",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Cluster Memory % Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{country=\"$country\", environment=\"$env\"} - node_memory_MemAvailable_bytes{country=\"$country\", environment=\"$env\"}) / sum(node_memory_MemTotal_bytes{country=\"$country\", environment=\"$env\"})) * 100",
     "legendFormat": "Used %"
    }
   ]
  },
  {
   "title": "Cluster Network RX/TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\"}[1m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Number of CPU Cores Utilized in the Cluster",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{country=\"$country\", environment= \"$env\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % Utilization Per Node",
     "type": "timeseries",
     "description": "CPU utilization in a cluster per node",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(avg(1-rate(node_cpu_seconds_total{mode=\"idle\", country=\"$country\", environment=\"$env\"}[1m])) by(instance)) * 100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU % Free",
     "type": "stat",
     "description": "Free CPU percentage",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", country=\"$country\", environment= \"$env\"}[1m])) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % Requests",
     "type": "stat",
     "description": "Total CPU percentage requests",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{unit=\"core\", country=\"$country\", environment= \"$env\"}) / sum(machine_cpu_cores{country=\"$country\", environment= \"$env\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU % Utilization Per Namespace",
     "type": "timeseries",
     "description": "CPU utilization in a cluster per namespace",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", country=\"$country\", environment=\"$env\"}[1m])) by (namespace)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU % Limits",
     "type": "stat",
     "description": "Total CPU percentage Limits",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_limits{unit=\"core\", country=\"$country\", environment= \"$env\"}) / sum(machine_cpu_cores{country=\"$country\", environment= \"$env\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": " Memory  % Utilization",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{country=\"$country\", environment=\"$env\"} - node_memory_MemAvailable_bytes{country=\"$country\", environment=\"$env\"}) / sum(node_memory_MemTotal_bytes{country=\"$country\", environment=\"$env\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization Per Node",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{country=\"$country\", environment=\"$env\"} - node_memory_MemAvailable_bytes{country=\"$country\", environment=\"$env\"}) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Memory  % Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{country=\"$country\", environment=\"$env\",unit=\"byte\"}) / sum(machine_memory_bytes{country=\"$country\", environment=\"$env\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Memory  % Limits",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_limits{country=\"$country\", environment=\"$env\",unit=\"byte\"}) / sum(machine_memory_bytes{country=\"$country\", environment=\"$env\"})) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization Per Namespace",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{image!=\"\", country=\"$country\", environment=\"$env\"}) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Network RX/TX Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\", namespace != \"\"}[1m])) by(instance)",
       "legendFormat": "{{instance}} Received"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\", namespace != \"\"}[1m])) by(instance)",
       "legendFormat": "{{ instance }} Transmitted"
      }
     ]
    },
    {
     "title": "Cluster Network RX/TX Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\", namespace != \"\"}[1m])) by(namespace)",
       "legendFormat": "{{instance}} Received"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lxc.*|veth.*\", country=\"$country\", environment=\"$env\", namespace != \"\"}[1m])) by(namespace)",
       "legendFormat": "{{ instance }} Transmitted"
      }
     ]
    }
   ]
  }
 ]
}