{
 "title": "2. Nodes",
 "description": "Displays Server Resources Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(up{service=\"k8s\"},country)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "prod-int : prod-int-cluster, prod : prod-cluster "
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(up{country=\"$country\", instance=~\".*$env\",service=\"k8s\",instance_state=\"running\"}, instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time the instance has been up since last reboot/boot.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{instance_id=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "description": "Total Disk Size",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance_id=\"$node\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Total RAM Size",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "description": "Total Number of CPUs",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{instance_id=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Percentage CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg by(mode, instance) (irate(node_cpu_seconds_total{instance_id = \"$node\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Load average measured on 1m, 5m and 15m interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance_id=\"$node\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance_id=\"$node\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "description": "Percentage Memory Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -(100 * (((node_memory_MemFree_bytes{instance_id=\"$node\"} + node_memory_Cached_bytes{instance_id=\"$node\"}+node_memory_Buffers_bytes{instance_id=\"$node\"}))/node_memory_MemTotal_bytes{instance_id=\"$node\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "100 * ((node_memory_MemFree_bytes{instance_id=\"$node\"} + node_memory_Cached_bytes{instance_id=\"$node\"}+node_memory_Buffers_bytes{instance_id=\"$node\"})/node_memory_MemTotal_bytes{instance_id=\"$node\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Breakdown",
   "type": "timeseries",
   "description": "Memory Utilization Breakdown",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_id=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance_id=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance_id=\"$node\"}) - ( node_memory_MemFree_bytes{instance_id=\"$node\"} + node_memory_Cached_bytes{instance_id=\"$node\"}+node_memory_Buffers_bytes{instance_id=\"$node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance_id=\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance_id=\"$node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance_id=\"$node\"} + node_memory_Cached_bytes{instance_id=\"$node\"}+node_memory_Buffers_bytes{instance_id=\"$node\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "timeseries",
   "description": "Swap Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance_id=\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance_id=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance_id=\"$node\"} - node_memory_SwapFree_bytes{instance_id=\"$node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Out Of Memory Kill Counter",
   "type": "timeseries",
   "description": "Shows number of times processes have been killed because of out of memory issue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(node_vmstat_oom_kill{instance_id=\"$node\"}[1m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "description": "Disk Usage Percentage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_avail_bytes{instance_id=\"$node\", mountpoint=\"/\"}/node_filesystem_size_bytes{instance_id=\"$node\", mountpoint=~\"/\"})",
     "legendFormat": "{{ instance }}:  Free"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "File Descriptors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance_id=\"$node\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "description": "Number of active processes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_procs_running{instance_id=\"$node\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "node_procs_blocked{instance_id=\"$node\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "Disk Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_id=\"$node\", mountpoint=~\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance_id=\"$node\", mountpoint=\"/\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Activities Rate",
   "type": "timeseries",
   "description": "Disk Successful Read  and Write rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance_id=\"$node\"}[1m])",
     "legendFormat": " {{ device }}:Reads"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance_id=\"$node\"}[1m])",
     "legendFormat": "{{device}}:Writes"
    }
   ]
  },
  {
   "title": "Disk Activities Count",
   "type": "timeseries",
   "description": "Disk Successful Number of Reads  and Writes ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance_id=\"$node\"}[1m])",
     "legendFormat": " {{device}}: Reads"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance_id=\"$node\"}[1m])",
     "legendFormat": "{{device}}: Writes"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Network Transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{instance_id=\"$node\", device=~\"ens.*|eth.*\"}[1m]))",
     "legendFormat": "rx/bytes"
    },
    {
     "expr": "sum by(instance) (rate(node_network_transmit_bytes_total{instance_id=\"$node\", device=~\"ens.*|eth.*\"}[1m]))",
     "legendFormat": "tx/bytes"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "description": "Network Packets Count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_network_receive_packets_total{instance_id=\"$node\", device=~\"ens.*|eth.*\"}[1m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum by(instance) (irate(node_network_transmit_packets_total{instance_id=\"$node\", device=~\"ens.*|eth.*\"}[1m]))",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}