{
 "title": "AWS ALB Golden Signals",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(aws_applicationelb_info, country)"
    }
   },
   {
    "name": "load_balancer",
    "label": "Load Balancer",
    "query": {
     "query": "label_values(aws_applicationelb_request_count_sum{country=\"$country\"}, dimension_LoadBalancer)"
    }
   },
   {
    "name": "target_group",
    "label": "Target Group",
    "query": {
     "query": "label_values(aws_applicationelb_healthy_host_count_average{country=\"$country\",dimension_LoadBalancer=~\".*$load_balancer.*\"}, dimension_TargetGroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "options": { "content": "\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "options": { "content": "\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors From the Load Balancer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_LoadBalancer) (aws_applicationelb_httpcode_elb_4_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum by (dimension_LoadBalancer) (aws_applicationelb_httpcode_elb_5_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\"})",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "4XX Errors From the Target Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_TargetGroup) (aws_applicationelb_httpcode_target_4_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_TargetGroup=~\".+$target_group.+\", dimension_AvailabilityZone=\"\"}) > 0",
     "legendFormat": "{{ dimension_TargetGroup }} - 4XX"
    }
   ]
  },
  {
   "title": "Average Target Groups Response Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_target_response_time_average{dimension_LoadBalancer=~\".+$load_balancer.+\",dimension_AvailabilityZone=\"\", dimension_TargetGroup=~\".+$target_group.+\"} > 0",
     "legendFormat": "{{dimension_TargetGroup}}"
    }
   ]
  },
  {
   "title": "Unhealthy Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_LoadBalancer, dimension_TargetGroup) (aws_applicationelb_un_healthy_host_count_average{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=~\".+$target_group.+\"}) > 0",
     "legendFormat": "{{  dimension_TargetGroup }}"
    }
   ]
  },
  {
   "title": "5XX Errors From the Target Groups",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (dimension_TargetGroup) (aws_applicationelb_httpcode_target_5_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_TargetGroup=~\".+$target_group.+\"}) > 0",
     "legendFormat": "{{ dimension_TargetGroup }} - 5XX"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "options": { "content": "\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy Hosts  in Target groups",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aws_applicationelb_healthy_host_count_average{dimension_LoadBalancer=~\".+$load_balancer.+\",dimension_AvailabilityZone=\"\", dimension_TargetGroup=~\".+$target_group.+\"}",
     "legendFormat": "{{dimension_TargetGroup}}"
    }
   ]
  },
  {
   "title": "Bytes processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_processed_bytes_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_AvailabilityZone!=\"\"}",
     "legendFormat": "{{ dimension_AvailabilityZone}}"
    }
   ]
  },
  {
   "title": "2XX Responses by Target Groups ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_2_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=~\".+$target_group.+\"} > 0",
     "legendFormat": "{{ dimension_TargetGroup }}"
    }
   ]
  },
  {
   "title": "Processed Requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_request_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_AvailabilityZone=\"\", dimension_TargetGroup=~\".+$target_group.+\"} > 0",
     "legendFormat": "{{dimension_TargetGroup}}"
    }
   ]
  },
  {
   "title": "3XX Responses by Target Groups ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_httpcode_target_3_xx_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\", dimension_TargetGroup=~\".+$target_group.+\", dimension_AvailabilityZone=\"\"} > 0",
     "legendFormat": "{{dimension_TargetGroup}}"
    },
    { "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_active_connection_count_sum{dimension_LoadBalancer=~\".+$load_balancer.+\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Rules Evaluated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_applicationelb_rule_evaluations_sum{dimension_LoadBalancer=~\".+$load_balancer.+\"}",
     "legendFormat": "Rules"
    }
   ]
  }
 ]
}