{
 "title": "3. Applications",
 "description": "Displays metrics for Koko Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "country", "label": "Country", "query": { "query": "label_values(up,country)" } },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(up{job=\"cadvisor\",country=\"$country\",instance_state=\"running\",platform != \"k8s\", instance !~ \".*cluster\"},instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance ID",
    "query": {
     "query": "label_values(machine_cpu_cores{instance=~\".*$server.*\",country=\"$country\",instance_state=\"running\"}, instance_id)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{instance_id=~\"$instance\",country=\"$country\"},container_label_com_docker_swarm_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name)(rate(container_cpu_usage_seconds_total{instance_id=~\"$instance\",name=~\"$container.*\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Container memory utilization",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance_id=~\"$instance\",name=~\"$container.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance_id=~\"$instance\",name=~\"$container.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "File descriptors showing number of open files",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "container_file_descriptors{instance_id=~\"$instance\", name=~\"$container.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Inodes",
   "type": "timeseries",
   "description": "Number of Inodes used, free and total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "container_fs_inodes_free{instance_id=~\"$instance\", name=~\"$container.*\"}",
     "legendFormat": "{{name}}: Free"
    },
    {
     "expr": "container_fs_inodes_total{instance_id=~\"$instance\", name=~\"$container.*\"}",
     "legendFormat": "{{name}}: Total"
    },
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "OOM Count",
   "type": "timeseries",
   "description": "Number of OOM instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "container_oom_events_total{instance_id=~\"$instance\", name=~\"$container.*\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum  by (name) (rate(container_network_receive_bytes_total{instance_id=~\"$instance\", name=~\"$container.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance_id=~\"$instance\",name=~\"$container.*\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "Running Hours of a container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance_id=~\"$instance\",name=~\"$container.*\"})/3600",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Versions",
   "type": "table",
   "description": "Versions in which containers are running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "label_replace(group by( image, name) (container_start_time_seconds{instance_id=~\"$instance\", name=~\"$container.*\"}), \"image\", \"$1\", \"image\", \".*:(.*)@.*\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}